/*
 * Posting API - version 1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartrecruiters.api.posting.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CustomField
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-05-16T20:12:05.632124+01:00[Europe/London]")
public class CustomField {
  public static final String SERIALIZED_NAME_FIELD_ID = "fieldId";
  @SerializedName(SERIALIZED_NAME_FIELD_ID)
  private String fieldId;

  public static final String SERIALIZED_NAME_FIELD_LABEL = "fieldLabel";
  @SerializedName(SERIALIZED_NAME_FIELD_LABEL)
  private String fieldLabel;

  public static final String SERIALIZED_NAME_VALUE_ID = "valueId";
  @SerializedName(SERIALIZED_NAME_VALUE_ID)
  private String valueId;

  public static final String SERIALIZED_NAME_VALUE_LABEL = "valueLabel";
  @SerializedName(SERIALIZED_NAME_VALUE_LABEL)
  private String valueLabel;


  public CustomField fieldId(String fieldId) {
    
    this.fieldId = fieldId;
    return this;
  }

   /**
   * Get fieldId
   * @return fieldId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFieldId() {
    return fieldId;
  }



  public void setFieldId(String fieldId) {
    this.fieldId = fieldId;
  }


  public CustomField fieldLabel(String fieldLabel) {
    
    this.fieldLabel = fieldLabel;
    return this;
  }

   /**
   * Get fieldLabel
   * @return fieldLabel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFieldLabel() {
    return fieldLabel;
  }



  public void setFieldLabel(String fieldLabel) {
    this.fieldLabel = fieldLabel;
  }


  public CustomField valueId(String valueId) {
    
    this.valueId = valueId;
    return this;
  }

   /**
   * Get valueId
   * @return valueId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getValueId() {
    return valueId;
  }



  public void setValueId(String valueId) {
    this.valueId = valueId;
  }


  public CustomField valueLabel(String valueLabel) {
    
    this.valueLabel = valueLabel;
    return this;
  }

   /**
   * Get valueLabel
   * @return valueLabel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getValueLabel() {
    return valueLabel;
  }



  public void setValueLabel(String valueLabel) {
    this.valueLabel = valueLabel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomField customField = (CustomField) o;
    return Objects.equals(this.fieldId, customField.fieldId) &&
        Objects.equals(this.fieldLabel, customField.fieldLabel) &&
        Objects.equals(this.valueId, customField.valueId) &&
        Objects.equals(this.valueLabel, customField.valueLabel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fieldId, fieldLabel, valueId, valueLabel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomField {\n");
    sb.append("    fieldId: ").append(toIndentedString(fieldId)).append("\n");
    sb.append("    fieldLabel: ").append(toIndentedString(fieldLabel)).append("\n");
    sb.append("    valueId: ").append(toIndentedString(valueId)).append("\n");
    sb.append("    valueLabel: ").append(toIndentedString(valueLabel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

