/*
 * Posting API - version 1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartrecruiters.api.posting.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
 * Gets or Sets JobAdLanguageCode
 */
@JsonAdapter(JobAdLanguageCode.Adapter.class)
public enum JobAdLanguageCode {
  
  AF("af"),
  
  AM("am"),
  
  AR("ar"),
  
  AZ("az"),
  
  BG("bg"),
  
  BN("bn"),
  
  CA("ca"),
  
  CS("cs"),
  
  CY("cy"),
  
  DA("da"),
  
  DE("de"),
  
  EL("el"),
  
  EN("en"),
  
  EN_GB("en-GB"),
  
  ES("es"),
  
  ES_MX("es-MX"),
  
  ET("et"),
  
  EU("eu"),
  
  FA("fa"),
  
  FI("fi"),
  
  FIL("fil"),
  
  FR("fr"),
  
  FR_CA("fr-CA"),
  
  GA("ga"),
  
  GL("gl"),
  
  GU("gu"),
  
  HE("he"),
  
  HI("hi"),
  
  HR("hr"),
  
  HU("hu"),
  
  HY("hy"),
  
  ID("id"),
  
  IS("is"),
  
  IT("it"),
  
  JA("ja"),
  
  KA("ka"),
  
  KM("km"),
  
  KN("kn"),
  
  KO("ko"),
  
  LO("lo"),
  
  LT("lt"),
  
  LV("lv"),
  
  ML("ml"),
  
  MN("mn"),
  
  MR("mr"),
  
  MS("ms"),
  
  NE("ne"),
  
  NL("nl"),
  
  NO("no"),
  
  PL("pl"),
  
  PT("pt"),
  
  PT_BR("pt-BR"),
  
  RO("ro"),
  
  RU("ru"),
  
  SI("si"),
  
  SK("sk"),
  
  SL("sl"),
  
  SR("sr"),
  
  SV("sv"),
  
  SW("sw"),
  
  TA("ta"),
  
  TE("te"),
  
  TR("tr"),
  
  UK("uk"),
  
  UR("ur"),
  
  VI("vi"),
  
  ZH_CN("zh-CN"),
  
  ZH_TW("zh-TW"),
  
  ZU("zu");

  private String value;

  JobAdLanguageCode(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static JobAdLanguageCode fromValue(String value) {
    for (JobAdLanguageCode b : JobAdLanguageCode.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<JobAdLanguageCode> {
    @Override
    public void write(final JsonWriter jsonWriter, final JobAdLanguageCode enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public JobAdLanguageCode read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return JobAdLanguageCode.fromValue(value);
    }
  }
}

